---

- hosts: all
  become: true
  tasks:

  - name: update packages and install tmux and httpd packages
    package:
      name: 
        - tmux
        - httpd
      state: latest
      update_cache: yes

